platform:ios, ‘8.0’
pod 'AMap3DMap'
pod 'AMapSearch'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'AFNetworking', '~> 3.0'

pod 'MJExtension'

pod 'BlocksKit'

pod 'Masonry'

pod 'Realm'

pod 'MBProgressHUD', '~> 0.9.2'